apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskcafe.fullname" . }}
  labels:
    {{- include "taskcafe.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "taskcafe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "taskcafe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taskcafe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TASKCAFE_DATABASE_HOST
              value: "{{ include "taskcafe.postgresql.fullname" . }}"
            - name: TASKCAFE_DATABASE_USER
              value: "postgres"
            - name: TASKCAFE_MIGRATE
              value: "true"
          volumeMounts:
            - name: app-config
              mountPath: /root/conf/app.toml
              subPath: app.toml
            - name: taskcafe-data
              mountPath: /root/uploads
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 120
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 120
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "taskcafe.fullname" . }}
        - name: taskcafe-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "taskcafe.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
